[nrf fromtree] net: ethernet: Fix build without -fpermissive
Fix ethernet_hw_caps initialization in ethernet.h for
strict type checking.

g++-12: include/zephyr/net/ethernet.h:957:38: error: invalid \
 conversion from 'int' to 'ethernet_hw_caps' [-fpermissive]

Signed-off-by: Daniel Nicoletti <dantti12@gmail.com>
(cherry picked from commit b4f940d654a223e8aaa283d74dddb4bdb554cf92)